<a href="https://colab.research.google.com/github/EbrahemHesham/EbrahemHesham/blob/main/Nymby_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
myarray=np.array([10,20,30,40])
print(myarray)
print(type(myarray))


[10 20 30 40]
<class 'numpy.ndarray'>


In [ ]:
print(myarray.shape)
print(myarray[0])
myarray[0]=3245
print(myarray[0])
print(myarray)

(4,)
3245
3245
[3245   20   30   40]


In [4]:
import numpy as np
my_array=np.array([[10,20,30,40],[50,60,70,80]])
print(my_array)
print(my_array.shape)
print(type(my_array))


[[10 20 30 40]
 [50 60 70 80]]
(2, 4)
<class 'numpy.ndarray'>


In [6]:
y=np.array([1,2,3,4,5,6])
print(y)
print(y[0:3])

[1 2 3 4 5 6]
[1 2 3]


In [12]:
xy=np.array([[10,20,30],[50,60,70]])
# print(xy)
print(xy[1:2,1:2])

[[60]]


In [24]:
zeroarray=np.zeros((3,3))
# print(zeroarray)
onarray=np.ones((3,3))
# print(onarray)
constant_type_array=np.full((3,3),7)
# print(constant_type_array)
eyearray=np.eye(4)
# print(eyearray)
# most important array is random array
Random_matrix=np.random.random((3,3))
# print(Random_matrix)
# print(Random_matrix[0:2])

[[0.18972819 0.5874934  0.36543859]
 [0.32717076 0.31222005 0.44310541]]


In [30]:
# Random_matrix=np.random.random((3,3),dtype=np.int64)

q=np.array([[1,2],[5,4]])
print(q.dtype)

s=np.random.random((3,3))
print(s.dtype)

f=np.array([1.3,2.4,4.5],dtype=np.int64)
print(f)

int64
float64
[1 2 4]


In [36]:
# Arithmetic operations
y=np.array([[1,2,3],[4,5,6]])
x=np.array([[10,20,30],[40,50,60]])
print(y.shape)
print(x.shape)




(2, 3)
(2, 3)


In [37]:
print(x+y)  

[[11 22 33]
 [44 55 66]]


In [38]:
print(np.add(x,y))

[[11 22 33]
 [44 55 66]]


In [39]:
print(np.subtract(x,y))

[[ 9 18 27]
 [36 45 54]]


In [40]:
print(np.multiply(x,y))

[[ 10  40  90]
 [160 250 360]]


In [41]:
print(np.divide(x,y))

[[10. 10. 10.]
 [10. 10. 10.]]


In [45]:
print(np.sqrt((y)))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [ ]:
print(y)

In [53]:
ynew=np.sqrt(y)
# print(ynew)
xnew=np.divide(y,x)
# print(xnew)
z=np.multiply(xnew,ynew)
print(z)

[[0.1        0.14142136 0.17320508]
 [0.2        0.2236068  0.24494897]]


In [58]:
# Dot product
import numpy as пр
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
v=np.array([9,10])
w = np.array([11, 12])
print( 'shape of x ',x.shape)
print('shape of y', y.shape)
print(v.dot(w))
print(x.dot(v))
print(x.dot(y))


shape of x  (2, 2)
shape of y (2, 2)
219
[29 67]
[[19 22]
 [43 50]]


In [64]:
# Transpose
import numpy as np
x=np.array([[1,2],[3,4]])
print('original matrix', x)
print('transpose matrix',x.T)

original matrix [[1 2]
 [3 4]]
transpose matrix [[1 3]
 [2 4]]


In [73]:
# Tile broadcasting
import numpy as пр
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array((1,0,1))
vv=np.tile(v,(4,1))
# print(vv)
sum_of_vectors=x+vv
print(sum_of_vectors)
# print(x)
# print(v)
# print(x.shape)
# print(v.shape)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [74]:
# Broadcasting without tile
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array((1,0,1))
sum=x+v
print(sum)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
